In [1]:
import numpy as np

In [2]:
x = np.array([0,1,2,3])
x

array([0, 1, 2, 3])

In [3]:
w = np.array([[0,1,2,3],[4, 5, 6, 7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
y = np.arange(8).reshape(4, 2)
y

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [11]:
x = np.array([0, 1, 2, 3])
#to square values
print(np.square(x))

# square root of a value
print(np.sqrt(x))

# cosine of each value
print(np.cos(x))


[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [12]:
x = np.array([0, 1, 2, 3])

# Find the maximum value.
print(np.max(x))

# Find the mimimum value.
print(np.min(x))

# Find the mean.

print(np.mean(x))

# Find the standard deviation of the input array.
print(np.std(x))

3
0
1.5
1.118033988749895
